# 언어와 jdk의 버전을 지정한다.
language: java

jdk:
  - zulu-11

env:
  global:
    - CODECOV_TOKEN=""

install: true

# feature/#13-testing 브랜치에 push 되면 수행되는 명령어이다.
# 프로젝트 내에 권한이 추가된 gradlew를 활용하여 clean, build를 진행한다.
script: "./gradlew clean build"

# Travis CI 서버의 Home
# gradle을 통하여 의존성을 받게 되면 이를 캐시하여 배포할 때 마다 다시 받지 않도록 설정한다.
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

#after_success:
#  - bash <(curl -s https://codecov.io/bash)

# 어느 브랜치가 push 될 때 수행할지 지정한다.
# 오직 feature/#13-testing 브랜치가 push될 때 수행하도록 지정하였다.
branches:
  only:
    - feature/#13-testing

notifications:
  email:
    recipients:
      - honeion2012@gmail.com